### ISSUE TITLE
travel_time with order==2 has failed

### ISSUE THREAD

**Issue by espdev** [espdev/scikit-mpe#1]
Currently, order ==  2 for computing travel time in scikit-fmm (v 2019.1.30) has a numerical issue and does not work properly: https://github.com/scikit-fmm/scikit-fmm/issues/28

The following code should be removed after fixing the issue in scikit-fmm:
https://github.com/espdev/scikit-mpe/blob/59551bae579a6e19b6e195b57c7f5ba252a065f3/skmpe/_parameters.py#L40-L47

And also in the tests:
https://github.com/espdev/scikit-mpe/blob/59551bae579a6e19b6e195b57c7f5ba252a065f3/tests/test_mpe.py#L13

**Comment by jkfurtney** [comment]
This should be fixed in scikit-fmm master, can you give it a try and let me know if you find any issues? Thanks

**Comment by espdev** [comment]
@jkfurtney I have checked my code from [refactoring-and-docs](https://github.com/espdev/scikit-mpe/tree/refactoring-and-docs) branch with scikit-fmm from master. It works fine! All tests with order 1 and 2 were completed successfully.

Thank you!
